import { useState } from 'react';
import './ConfirmationForm.css';

// ConfirmationForm shows the AI-extracted email fields in editable inputs.
// Props:
//   initialData    — { to, subject, body } from the AI parser
//   toConfidence   — 'high' | 'low' — GPT's confidence in the extracted email address
//   onSend(data)   — called with final { to, subject, body } when user clicks Send
//   onBack()       — called when user wants to go back and re-compose
//   isSending      — true while the email is being sent (disables the form)
function ConfirmationForm({ initialData, toConfidence, onSend, onBack, isSending }) {
  const [to, setTo] = useState(initialData.to);
  const [subject, setSubject] = useState(initialData.subject);
  const [body, setBody] = useState(initialData.body);

  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  const isToValid = emailRegex.test(to.trim());
  const isToEmpty = to.trim() === '';

  const canSend = isToValid && subject.trim() !== '' && body.trim() !== '' && !isSending;

  const wordCount = body.trim() === '' ? 0 : body.trim().split(/\s+/).length;

  // Show the confidence warning when:
  //   - GPT flagged low confidence, AND
  //   - The field has a value (if it's empty, the "please enter one" hint covers it)
  //   - The user hasn't corrected it yet (we dismiss the warning once the value changes)
  const [userEditedTo, setUserEditedTo] = useState(false);
  const showConfidenceWarning = toConfidence === 'low' && !isToEmpty && !userEditedTo;

  function handleToChange(e) {
    setTo(e.target.value);
    setUserEditedTo(true); // user took ownership — dismiss the warning
  }

  function handleSubmit(e) {
    e.preventDefault();
    if (!canSend) return;
    onSend({ to: to.trim(), subject: subject.trim(), body: body.trim() });
  }

  return (
    <div className="confirmation-form">
      <div className="confirmation-form__header">
        <h2 className="confirmation-form__title">Review your email</h2>
        <p className="confirmation-form__subtitle">
          The AI has drafted this from your input. Edit anything before sending.
        </p>
      </div>

      <div className="ai-badge" aria-label="Generated by AI">
        <span className="ai-badge__icon">✦</span>
        Drafted by AI — review before sending
      </div>

      <form onSubmit={handleSubmit} className="confirmation-form__fields">

        {/* To */}
        <div className="field">
          <label className="field__label" htmlFor="field-to">To</label>
          <input
            id="field-to"
            type="email"
            className={`field__input
              ${!isToEmpty && !isToValid ? 'field__input--error' : ''}
              ${showConfidenceWarning ? 'field__input--warning' : ''}
            `}
            value={to}
            onChange={handleToChange}
            placeholder="recipient@example.com"
            disabled={isSending}
            autoComplete="email"
          />

          {/* Priority order: format error > confidence warning > empty hint */}
          {!isToEmpty && !isToValid && (
            <p className="field__error" role="alert">
              Please enter a valid email address.
            </p>
          )}
          {showConfidenceWarning && (
            <p className="field__confidence-warning" role="alert">
              ⚠ AI wasn&apos;t certain about this address — please verify it before sending.
            </p>
          )}
          {isToEmpty && (
            <p className="field__hint">
              The AI couldn&apos;t find an email address — please enter one.
            </p>
          )}
        </div>

        {/* Subject */}
        <div className="field">
          <label className="field__label" htmlFor="field-subject">Subject</label>
          <input
            id="field-subject"
            type="text"
            className="field__input"
            value={subject}
            onChange={(e) => setSubject(e.target.value)}
            placeholder="Email subject"
            disabled={isSending}
          />
        </div>

        {/* Body */}
        <div className="field">
          <div className="field__label-row">
            <label className="field__label" htmlFor="field-body">Message</label>
            <span className="field__word-count">{wordCount} {wordCount === 1 ? 'word' : 'words'}</span>
          </div>
          <textarea
            id="field-body"
            className="field__textarea"
            value={body}
            onChange={(e) => setBody(e.target.value)}
            placeholder="Email body"
            rows={8}
            disabled={isSending}
          />
        </div>

        {/* Actions */}
        <div className="confirmation-form__actions">
          <button
            type="button"
            className="btn btn--ghost"
            onClick={onBack}
            disabled={isSending}
          >
            ← Back
          </button>

          <button
            type="submit"
            className="btn btn--primary"
            disabled={!canSend}
          >
            {isSending ? (
              <>
                <span className="btn__spinner" aria-hidden="true" />
                Sending...
              </>
            ) : (
              <>
                Send Email
                <span className="btn__arrow" aria-hidden="true">→</span>
              </>
            )}
          </button>
        </div>
      </form>
    </div>
  );
}

export default ConfirmationForm;
